SRC += features/orbital_mouse.c

AUTO_SHIFT_ENABLE = yes
CAPS_WORD_ENABLE = yes
EXTRAKEY_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes

MOUSEKEY_ENABLE = no
MOUSE_ENABLE = yes
